### ISSUE TITLE
crashes when tasks are removed from experiment.enable_tasks

### ISSUE THREAD

**Issue by pingings** [dicelab-rhul/matbii#11]
e.g. when "system_monitoring" is removed from this field in the config file:

```
Traceback (most recent call last):
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\__main__.py", line 169, in <module>
    env.run()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 46, in run
    asyncio.run(_run())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 44, in _run
    await asyncio.gather(*self.get_schedule())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 69, in _loop
    running = await self.step()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 82, in step
    await self._step(agents)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 88, in _step_sync
    await _Future.gather([agent.__cycle__() for agent in agents])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 22, in gather
    return await asyncio.gather(*(future.__await__() for future in futures))
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 88, in __await__
    return (yield from self._future.__await__())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 28, in call_sync
    result = func(*args, **kwargs)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\agent_default.py", line 119, in __cycle__
    super().__cycle__()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\agent\agent_routed.py", line 292, in __cycle__
    self.__observe__()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\agent\agent_routed.py", line 317, in __observe__
    for observation in sensor.iter_observations():
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\icua\agent\acceptability.py", line 132, in iter_observations
    is_acceptable=self.is_acceptable(),
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_system_monitoring.py", line 71, in is_acceptable
    return all([x() for x in self._is_subtask_acceptable_map.values()])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_system_monitoring.py", line 71, in <listcomp>
    return all([x() for x in self._is_subtask_acceptable_map.values()])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_system_monitoring.py", line 110, in is_light_acceptable
    return [self._is_light1_acceptable, self._is_light2_acceptable][_id - 1]()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_system_monitoring.py", line 114, in _is_light1_acceptable
    return self.beliefs[light_id(1)]["data-state"] == SetLightAction.ON
KeyError: 'light-1-button'

**Comment by pingings** [comment]
when "resource_management" is removed:

```
Traceback (most recent call last):
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\__main__.py", line 169, in <module>
    env.run()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 46, in run
    asyncio.run(_run())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 44, in _run
    await asyncio.gather(*self.get_schedule())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 69, in _loop
    running = await self.step()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 82, in step
    await self._step(agents)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 88, in _step_sync
    await _Future.gather([agent.__cycle__() for agent in agents])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 22, in gather
    return await asyncio.gather(*(future.__await__() for future in futures))
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 88, in __await__
    return (yield from self._future.__await__())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 28, in call_sync
    result = func(*args, **kwargs)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\agent_default.py", line 119, in __cycle__
    super().__cycle__()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\agent\agent_routed.py", line 292, in __cycle__
    self.__observe__()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\agent\agent_routed.py", line 317, in __observe__
    for observation in sensor.iter_observations():
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\icua\agent\acceptability.py", line 132, in iter_observations
    is_acceptable=self.is_acceptable(),
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_resource_management.py", line 46, in is_acceptable
    return all([x() for x in self._is_subtask_acceptable_map.values()])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_resource_management.py", line 46, in <listcomp>
    return all([x() for x in self._is_subtask_acceptable_map.values()])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_resource_management.py", line 68, in is_tank_acceptable
    tank = self.beliefs[tank_id(_id)]
KeyError: 'tank-a'
```

when "tracking" is removed:
```
Traceback (most recent call last):
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\__main__.py", line 169, in <module>
    env.run()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 46, in run
    asyncio.run(_run())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 44, in _run
    await asyncio.gather(*self.get_schedule())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 69, in _loop
    running = await self.step()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 82, in step
    await self._step(agents)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\environment\environment.py", line 88, in _step_sync
    await _Future.gather([agent.__cycle__() for agent in agents])
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 22, in gather
    return await asyncio.gather(*(future.__await__() for future in futures))
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 88, in __await__
    return (yield from self._future.__await__())
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\utils\_async.py", line 28, in call_sync
    result = func(*args, **kwargs)
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\agent_default.py", line 119, in __cycle__
    super().__cycle__()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\agent\agent_routed.py", line 292, in __cycle__
    self.__observe__()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\star_ray\agent\agent_routed.py", line 317, in __observe__
    for observation in sensor.iter_observations():
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\icua\agent\acceptability.py", line 132, in iter_observations
    is_acceptable=self.is_acceptable(),
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_tracking.py", line 27, in is_acceptable
    return self.is_tracking_acceptable()
  File "C:\Users\szonya\anaconda3\envs\matbii\lib\site-packages\matbii\guidance\sensor_tracking.py", line 48, in is_tracking_acceptable
    raise ValueError(
ValueError: Failed to determine acceptability of task: 'tracking'.
-- Missing beliefs for elements: 'tracking_target' and/or 'tracking_box'
```

**Comment by BenedictWilkins** [comment]
I believe this is fixed now, it was an issue with the guidance agent and active/enabled tasks.
