### ISSUE TITLE
program doesn't run if no eye tracker connected

### ISSUE THREAD

**Issue by pingings** [dicelab-rhul/matbii#8]
Throws this error instead of allowing the program to run without eyetracking features:

``` Traceback (most recent call last):
  File "C:\Users\Admin\.conda\envs\matbii\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\.conda\envs\matbii\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\.conda\envs\matbii\lib\site-packages\matbii\__main__.py", line 91, in <module>
    eyetracking_sensor = config.eyetracking.new_eyetracking_sensor()
  File "C:\Users\Admin\.conda\envs\matbii\lib\site-packages\matbii\config\__init__.py", line 160, in new_eyetracking_sensor
    eyetracker = self.new_eyetracker()
  File "C:\Users\Admin\.conda\envs\matbii\lib\site-packages\matbii\config\__init__.py", line 174, in new_eyetracker
    return self._new_tobii_eyetracker()
  File "C:\Users\Admin\.conda\envs\matbii\lib\site-packages\matbii\config\__init__.py", line 184, in _new_tobii_eyetracker
    return tobii.TobiiEyetracker(uri=self.uri)
  File "C:\Users\Admin\.conda\envs\matbii\lib\site-packages\icua\extras\eyetracking\tobii.py", line 87, in __init__
    raise EyetrackingConfigurationError(
icua.extras.eyetracking.error.EyetrackingConfigurationError: No eyetrackers were found, check that the eyetracker is connected and avaliable in the official Tobii Pro Eye Tracker Manager software.

**Comment by BenedictWilkins** [comment]
@pingings this only happens if you enable eye tracking in the configuration? i.e. I guess this should be default behaviour to let people know that the eye tracker was not set up correctly?
```
"eyetracking": {
  "uri": null,
  "sdk": "tobii",
  "enabled": true
  "moving_average_n": 5,
  "velocity_threshold": 0.5
}
```
